# Generated by Django 4.1.7 on 2023-03-01 15:57

import API.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=100)),
                ("image_url", models.CharField(default="", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shop_name", models.CharField(default="", max_length=100)),
                ("full_name", models.CharField(default="", max_length=100)),
                ("image_url", models.CharField(default="", max_length=1000)),
                ("phone_number", models.CharField(default="", max_length=20)),
                ("password", models.CharField(default="", max_length=100)),
                ("e_mail", models.CharField(default="", max_length=100)),
                ("wilaya", models.CharField(default="", max_length=100)),
                ("commune", models.CharField(default="", max_length=100)),
                ("address", models.CharField(default="", max_length=100)),
                ("created_at", models.IntegerField(default=API.models.get_now_stamp)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("string", models.CharField(max_length=100)),
                ("discount", models.IntegerField(default=0)),
                (
                    "coupon_type",
                    models.CharField(
                        choices=[
                            ("Product", "Product"),
                            ("Category", "Category"),
                            ("All", "All"),
                        ],
                        default="All",
                        max_length=100,
                    ),
                ),
                ("target_id", models.IntegerField(blank=True, default=None, null=True)),
                ("max_nbr_uses", models.IntegerField(default=1)),
                ("created_at", models.IntegerField(default=API.models.get_now_stamp)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.IntegerField(default=API.models.get_now_stamp)),
                ("total_price", models.FloatField(default=0.0)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        related_query_name="order",
                        to="API.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PackType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_name", models.CharField(default="", max_length=100)),
                ("full_name", models.CharField(default="", max_length=100)),
                ("image_url", models.CharField(default="", max_length=1000)),
                ("phone_number", models.CharField(default="", max_length=20)),
                ("password", models.CharField(default="", max_length=100)),
                ("e_mail", models.CharField(default="", max_length=100)),
                ("wilaya", models.CharField(default="", max_length=100)),
                ("commune", models.CharField(default="", max_length=100)),
                ("address", models.CharField(default="", max_length=100)),
                ("created_at", models.IntegerField(default=API.models.get_now_stamp)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("fav_clients_list", models.ManyToManyField(to="API.client")),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=100)),
                ("brand", models.CharField(default="", max_length=100)),
                ("price", models.FloatField()),
                ("image_url", models.CharField(default="", max_length=100)),
                ("description", models.TextField(default="")),
                ("nbr_units", models.IntegerField(default=1)),
                ("discount", models.IntegerField(default=0)),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.IntegerField(default=API.models.get_now_stamp)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        related_query_name="product",
                        to="API.category",
                    ),
                ),
                (
                    "pack_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        related_query_name="product",
                        to="API.packtype",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        related_query_name="product",
                        to="API.store",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Created", "Created"),
                            ("Updated", "Updated"),
                            ("Deleted", "Deleted"),
                            ("Accepted", "Accepted"),
                            ("Refused", "Refused"),
                            ("Canceled", "Canceled"),
                            ("Submited", "Submited"),
                            ("Sent", "Sent"),
                            ("Completed", "Completed"),
                            ("Started Shipping", "Started Shipping"),
                            ("Delivered", "Delivered"),
                        ],
                        default="Created",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(default="")),
                ("time_stamp", models.IntegerField(default=API.models.get_now_stamp)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orderstates",
                        related_query_name="orderstate",
                        to="API.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("discount", models.IntegerField(default=0)),
                ("original_price", models.FloatField()),
                ("new_price", models.FloatField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orderitems",
                        related_query_name="orderitem",
                        to="API.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orderitems",
                        related_query_name="orderitem",
                        to="API.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderCoupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordercoupons",
                        related_query_name="ordercoupon",
                        to="API.coupon",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordercoupons",
                        related_query_name="ordercoupon",
                        to="API.order",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                related_query_name="order",
                to="API.store",
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("Created", "Created"),
                            ("Updated", "Updated"),
                            ("Deleted", "Deleted"),
                            ("Accepted", "Accepted"),
                            ("Refused", "Refused"),
                            ("Canceled", "Canceled"),
                            ("Submited", "Submited"),
                            ("Sent", "Sent"),
                            ("Completed", "Completed"),
                            ("Started Shipping", "Started Shipping"),
                            ("Delivered", "Delivered"),
                        ],
                        default="Create",
                        max_length=100,
                    ),
                ),
                ("message", models.TextField(default="")),
                ("seen", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        related_query_name="notification",
                        to="API.client",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        related_query_name="notification",
                        to="API.store",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=100)),
                ("created_at", models.IntegerField(default=API.models.get_now_stamp)),
                ("clients_list", models.ManyToManyField(to="API.client")),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        related_query_name="group",
                        to="API.store",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CouponCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(default=0)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="couponcounts",
                        related_query_name="couponcount",
                        to="API.client",
                    ),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="couponcounts",
                        related_query_name="couponcount",
                        to="API.coupon",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="coupon",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coupons",
                related_query_name="coupon",
                to="API.store",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="fav_stores_list",
            field=models.ManyToManyField(to="API.store"),
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cartitems",
                        related_query_name="cartitem",
                        to="API.cart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cartitems",
                        related_query_name="cartitem",
                        to="API.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cart",
            name="client",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart",
                related_query_name="cart",
                to="API.client",
            ),
        ),
        migrations.AddConstraint(
            model_name="coupon",
            constraint=models.UniqueConstraint(
                fields=("string", "store_id"), name="unique_coupon"
            ),
        ),
    ]
