# Generated by Django 4.1.7 on 2023-03-29 17:52

import API.some_functions
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(default="", max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ad_type",
                    models.CharField(
                        choices=[("Store", "store"), ("Product", "product")],
                        default="Store",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "created_at",
                    models.IntegerField(default=API.some_functions.get_now_stamp),
                ),
                ("dir_path", models.CharField(default="", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=100)),
                ("image_url", models.CharField(default="", max_length=100)),
                ("dir_path", models.CharField(default="", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shop_name", models.CharField(default="", max_length=100)),
                ("full_name", models.CharField(default="", max_length=100)),
                ("image_url", models.CharField(default="", max_length=1000)),
                ("phone_number", models.CharField(default="", max_length=20)),
                ("password", models.CharField(default="", max_length=100)),
                ("e_mail", models.CharField(default="", max_length=100)),
                ("wilaya", models.CharField(default="", max_length=100)),
                ("commune", models.CharField(default="", max_length=100)),
                ("address", models.CharField(default="", max_length=100)),
                (
                    "created_at",
                    models.IntegerField(default=API.some_functions.get_now_stamp),
                ),
                ("dir_path", models.CharField(default="", max_length=100)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ClientFavStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClientNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("Created", "Created"),
                            ("Updated", "Updated"),
                            ("Deleted", "Deleted"),
                            ("Accepted", "Accepted"),
                            ("Refused", "Refused"),
                            ("Canceled", "Canceled"),
                            ("Submited", "Submited"),
                            ("Sent", "Sent"),
                            ("Completed", "Completed"),
                            ("Started Shipping", "Started Shipping"),
                            ("Delivered", "Delivered"),
                        ],
                        default="Created",
                        max_length=100,
                    ),
                ),
                ("message", models.TextField(default="")),
                ("seen", models.BooleanField(default=False)),
                (
                    "created_at",
                    models.IntegerField(default=API.some_functions.get_now_stamp),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClientProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("string", models.CharField(max_length=100)),
                ("discount", models.IntegerField(default=1)),
                (
                    "coupon_type",
                    models.CharField(
                        choices=[
                            ("product", "product"),
                            ("category", "category"),
                            ("all", "all"),
                        ],
                        default="all",
                        max_length=100,
                    ),
                ),
                ("target_id", models.IntegerField(blank=True, default=None, null=True)),
                ("max_nbr_uses", models.IntegerField(default=1)),
                (
                    "created_at",
                    models.IntegerField(default=API.some_functions.get_now_stamp),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="CouponClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=100)),
                (
                    "created_at",
                    models.IntegerField(default=API.some_functions.get_now_stamp),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GroupClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.IntegerField(default=API.some_functions.get_now_stamp),
                ),
                ("total_price", models.FloatField(default=1.0)),
                ("archived_by_store", models.BooleanField(default=False)),
                ("archived_by_client", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="OrderCoupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("discount", models.IntegerField(default=0)),
                ("original_price", models.FloatField()),
                ("new_price", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="OrderState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Created", "Created"),
                            ("Updated", "Updated"),
                            ("Deleted", "Deleted"),
                            ("Accepted", "Accepted"),
                            ("Refused", "Refused"),
                            ("Canceled", "Canceled"),
                            ("Submited", "Submited"),
                            ("Sent", "Sent"),
                            ("Completed", "Completed"),
                            ("Started Shipping", "Started Shipping"),
                            ("Delivered", "Delivered"),
                        ],
                        default="Created",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(default="")),
                (
                    "time_stamp",
                    models.IntegerField(default=API.some_functions.get_now_stamp),
                ),
                ("updated_by_store", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="PackType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_name", models.CharField(default="", max_length=100)),
                ("full_name", models.CharField(default="", max_length=100)),
                ("image_url", models.CharField(default="", max_length=1000)),
                ("phone_number", models.CharField(default="", max_length=20)),
                ("password", models.CharField(default="", max_length=100)),
                ("e_mail", models.CharField(default="", max_length=100)),
                ("wilaya", models.CharField(default="", max_length=100)),
                ("commune", models.CharField(default="", max_length=100)),
                ("address", models.CharField(default="", max_length=100)),
                (
                    "created_at",
                    models.IntegerField(default=API.some_functions.get_now_stamp),
                ),
                ("dir_path", models.CharField(default="", max_length=100)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "account",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="store",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StoreNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("Created", "Created"),
                            ("Updated", "Updated"),
                            ("Deleted", "Deleted"),
                            ("Accepted", "Accepted"),
                            ("Refused", "Refused"),
                            ("Canceled", "Canceled"),
                            ("Submited", "Submited"),
                            ("Sent", "Sent"),
                            ("Completed", "Completed"),
                            ("Started Shipping", "Started Shipping"),
                            ("Delivered", "Delivered"),
                        ],
                        default="Created",
                        max_length=100,
                    ),
                ),
                ("message", models.TextField(default="")),
                ("seen", models.BooleanField(default=False)),
                (
                    "created_at",
                    models.IntegerField(default=API.some_functions.get_now_stamp),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        related_query_name="notification",
                        to="API.store",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StoreFavClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="API.client"
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storefavclients",
                        related_query_name="storefavclient",
                        to="API.store",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="store",
            name="fav_clients",
            field=models.ManyToManyField(through="API.StoreFavClient", to="API.client"),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=100)),
                ("brand", models.CharField(default="", max_length=100)),
                ("price", models.FloatField()),
                ("image_url", models.CharField(default="", max_length=100)),
                ("description", models.TextField(default="")),
                ("nbr_units", models.IntegerField(default=1)),
                ("discount", models.IntegerField(default=0)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.IntegerField(default=API.some_functions.get_now_stamp),
                ),
                ("dir_path", models.CharField(default="", max_length=100)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        related_query_name="product",
                        to="API.category",
                    ),
                ),
                (
                    "pack_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        related_query_name="product",
                        to="API.packtype",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        related_query_name="product",
                        to="API.store",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="packtype",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_pack_type_name"
            ),
        ),
        migrations.AddField(
            model_name="orderstate",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orderstates",
                related_query_name="orderstate",
                to="API.order",
            ),
        ),
        migrations.AddField(
            model_name="orderproduct",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orderproducts",
                related_query_name="orderproduct",
                to="API.order",
            ),
        ),
        migrations.AddField(
            model_name="orderproduct",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orderproducts",
                related_query_name="orderproduct",
                to="API.product",
            ),
        ),
        migrations.AddField(
            model_name="ordercoupon",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ordercoupons",
                related_query_name="ordercoupon",
                to="API.coupon",
            ),
        ),
        migrations.AddField(
            model_name="ordercoupon",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordercoupons",
                related_query_name="ordercoupon",
                to="API.order",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                related_query_name="order",
                to="API.client",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="coupons",
            field=models.ManyToManyField(through="API.OrderCoupon", to="API.coupon"),
        ),
        migrations.AddField(
            model_name="order",
            name="current_state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_orders",
                related_query_name="current_order",
                to="API.orderstate",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(through="API.OrderProduct", to="API.product"),
        ),
        migrations.AddField(
            model_name="order",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                related_query_name="order",
                to="API.store",
            ),
        ),
        migrations.AddField(
            model_name="groupclient",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groupclients",
                related_query_name="groupclient",
                to="API.client",
            ),
        ),
        migrations.AddField(
            model_name="groupclient",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groupclients",
                related_query_name="groupclient",
                to="API.group",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="clients",
            field=models.ManyToManyField(through="API.GroupClient", to="API.client"),
        ),
        migrations.AddField(
            model_name="group",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                related_query_name="group",
                to="API.store",
            ),
        ),
        migrations.AddField(
            model_name="couponclient",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="couponclients",
                related_query_name="couponclient",
                to="API.client",
            ),
        ),
        migrations.AddField(
            model_name="couponclient",
            name="coupon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="couponclients",
                related_query_name="couponclient",
                to="API.coupon",
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="clients",
            field=models.ManyToManyField(through="API.CouponClient", to="API.client"),
        ),
        migrations.AddField(
            model_name="coupon",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coupons",
                related_query_name="coupon",
                to="API.store",
            ),
        ),
        migrations.AddField(
            model_name="clientproduct",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clientproducts",
                related_query_name="clientproduct",
                to="API.client",
            ),
        ),
        migrations.AddField(
            model_name="clientproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clientproducts",
                related_query_name="clientproduct",
                to="API.product",
            ),
        ),
        migrations.AddField(
            model_name="clientnotification",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                related_query_name="notification",
                to="API.client",
            ),
        ),
        migrations.AddField(
            model_name="clientfavstore",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clientfavstores",
                related_query_name="clientfavstore",
                to="API.client",
            ),
        ),
        migrations.AddField(
            model_name="clientfavstore",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="API.store"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="account",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="fav_stores",
            field=models.ManyToManyField(through="API.ClientFavStore", to="API.store"),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_category_name"
            ),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ads",
                related_query_name="ad",
                to="API.product",
            ),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ads",
                related_query_name="ad",
                to="API.store",
            ),
        ),
        migrations.AddField(
            model_name="adimage",
            name="ad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                related_query_name="image",
                to="API.advertisement",
            ),
        ),
        migrations.AddConstraint(
            model_name="storefavclient",
            constraint=models.UniqueConstraint(
                fields=("store_id", "client_id"), name="unique_store_client"
            ),
        ),
        migrations.AddConstraint(
            model_name="store",
            constraint=models.UniqueConstraint(
                fields=("store_name",), name="unique_store_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="store",
            constraint=models.UniqueConstraint(
                fields=("phone_number",), name="unique_store_phone_numbre"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("name", "store_id"), name="unique_product_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                check=models.Q(("price__gte", 1)), name="positive_price"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                check=models.Q(("nbr_units__gte", 1)), name="positive_nbr_units"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                check=models.Q(("discount__gte", 0), ("discount__lte", 100)),
                name="correct_product_discount",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderproduct",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity__gte", 1)), name="product_positive_quantity"
            ),
        ),
        migrations.AddConstraint(
            model_name="orderproduct",
            constraint=models.CheckConstraint(
                check=models.Q(("original_price__gte", 1)),
                name="product_positive_original_price",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderproduct",
            constraint=models.CheckConstraint(
                check=models.Q(("new_price__gte", 0)), name="product_positive_new_price"
            ),
        ),
        migrations.AddConstraint(
            model_name="orderproduct",
            constraint=models.CheckConstraint(
                check=models.Q(("discount__gte", 0), ("discount__lt", 100)),
                name="product_correct_discount",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                check=models.Q(("total_price__gte", 1)),
                name="order_positive_total_price",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("client_id__isnull", False),
                    ("store_id__isnull", False),
                    _connector="OR",
                ),
                name="valide_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="groupclient",
            constraint=models.UniqueConstraint(
                fields=("group_id", "client_id"), name="unique_group_client"
            ),
        ),
        migrations.AddConstraint(
            model_name="group",
            constraint=models.UniqueConstraint(
                fields=("name", "store_id"), name="unique_group_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="couponclient",
            constraint=models.UniqueConstraint(
                fields=("client_id", "coupon_id"), name="unique_client_coupon"
            ),
        ),
        migrations.AddConstraint(
            model_name="couponclient",
            constraint=models.CheckConstraint(
                check=models.Q(("count__gte", 0)), name="coupon_positive_count"
            ),
        ),
        migrations.AddConstraint(
            model_name="coupon",
            constraint=models.UniqueConstraint(
                fields=("string", "store_id"), name="unique_coupon"
            ),
        ),
        migrations.AddConstraint(
            model_name="coupon",
            constraint=models.CheckConstraint(
                check=models.Q(("max_nbr_uses__gte", 1)), name="positive_max_nbr_uses"
            ),
        ),
        migrations.AddConstraint(
            model_name="coupon",
            constraint=models.CheckConstraint(
                check=models.Q(("discount__gte", 1), ("discount__lte", 100)),
                name="correct_coupon_discount",
            ),
        ),
        migrations.AddConstraint(
            model_name="clientproduct",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity__gte", 1)), name="cart_positive_quantity"
            ),
        ),
        migrations.AddConstraint(
            model_name="clientfavstore",
            constraint=models.UniqueConstraint(
                fields=("client_id", "store_id"), name="unique_client_store"
            ),
        ),
        migrations.AddConstraint(
            model_name="client",
            constraint=models.UniqueConstraint(
                fields=("shop_name",), name="unique_shop_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="client",
            constraint=models.UniqueConstraint(
                fields=("phone_number",), name="unique_shop_phone_numbre"
            ),
        ),
        migrations.AddConstraint(
            model_name="advertisement",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("ad_type__iexact", "product"),
                    ("product_id__isnull", False),
                    _negated=True,
                ),
                name="valide_ad",
            ),
        ),
    ]
