# Generated by Django 4.1.7 on 2023-03-02 03:34

import API.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0002_alter_notification_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.IntegerField(default=API.models.get_now_stamp),
        ),
    ]
