# Generated by Django 4.0 on 2023-02-11 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_rename_commune_client_daira_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='daira',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='wilaya',
            new_name='province',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='daira',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='wilaya',
            new_name='province',
        ),
        migrations.AddField(
            model_name='product',
            name='store_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.store'),
        ),
    ]
