# Generated by Django 4.1.7 on 2023-03-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0002_remove_cart_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="items",
            field=models.ManyToManyField(through="API.CartProduct", to="API.product"),
        ),
    ]
