# Generated by Django 4.1.7 on 2023-03-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0003_alter_notification_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity__gte", 1)), name="positive_quantity_2"
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_category_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="client",
            constraint=models.UniqueConstraint(
                fields=("shop_name",), name="unique_shop_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="client",
            constraint=models.UniqueConstraint(
                fields=("phone_number",), name="unique_shop_phone_numbre"
            ),
        ),
        migrations.AddConstraint(
            model_name="coupon",
            constraint=models.CheckConstraint(
                check=models.Q(("max_nbr_uses__gte", 1)), name="positive_max_nbr_uses"
            ),
        ),
        migrations.AddConstraint(
            model_name="coupon",
            constraint=models.CheckConstraint(
                check=models.Q(("discount__gte", 0), ("discount__lte", 100)),
                name="correct_coupon_discount",
            ),
        ),
        migrations.AddConstraint(
            model_name="group",
            constraint=models.UniqueConstraint(
                fields=("name", "store_id"), name="unique_group_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("client_id__isnull", True),
                    ("store_id__isnull", True),
                    _connector="XOR",
                ),
                name="valide_notification",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                check=models.Q(("total_price__gte", 1)), name="positive_total_price"
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity__gte", 1)), name="positive_quantity"
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                check=models.Q(("original_price__gte", 1)),
                name="positive_original_price",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                check=models.Q(("new_price__gte", 0)), name="positive_new_price"
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                check=models.Q(("discount__gte", 0), ("discount__lte", 100)),
                name="correct_item_discount",
            ),
        ),
        migrations.AddConstraint(
            model_name="packtype",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_pack_type_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("name", "store_id"), name="unique_product_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                check=models.Q(("price__gte", 1)), name="positive_price"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                check=models.Q(("nbr_units__gte", 1)), name="positive_nbr_units"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                check=models.Q(("discount__gte", 0), ("discount__lte", 100)),
                name="correct_product_discount",
            ),
        ),
        migrations.AddConstraint(
            model_name="store",
            constraint=models.UniqueConstraint(
                fields=("store_name",), name="unique_store_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="store",
            constraint=models.UniqueConstraint(
                fields=("phone_number",), name="unique_store_phone_numbre"
            ),
        ),
    ]
