# Generated by Django 4.0 on 2023-02-11 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_rename_daira_client_district_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='store_id',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='store_id',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='store_id',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='store_id',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='usedcoupon',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='usedcoupon',
            old_name='coupon_id',
            new_name='coupon',
        ),
        migrations.RenameField(
            model_name='usedcoupon',
            old_name='order_id',
            new_name='order',
        ),
    ]
