# Generated by Django 4.0 on 2023-02-11 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_rename_store_id_coupon_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
