# Generated by Django 4.1.7 on 2023-03-20 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0004_remove_client_fav_stores_remove_store_fav_clients"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreFavClients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="API.client"
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storefavclients",
                        related_query_name="storefavclient",
                        to="API.store",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="store",
            name="fav_clients",
            field=models.ManyToManyField(
                through="API.StoreFavClients", to="API.client"
            ),
        ),
        migrations.AddConstraint(
            model_name="storefavclients",
            constraint=models.UniqueConstraint(
                fields=("store_id", "client_id"), name="unique_store_client"
            ),
        ),
    ]
