# Generated by Django 4.1.7 on 2023-03-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0004_alter_order_total_price_cartitem_positive_quantity_2_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="orderitem",
            name="correct_item_discount",
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                check=models.Q(("discount__gte", 0), ("discount__lt", 100)),
                name="correct_item_discount",
            ),
        ),
    ]
