# Generated by Django 4.1.7 on 2023-03-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0005_remove_orderitem_correct_item_discount_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cartitem",
            name="positive_quantity_2",
        ),
        migrations.RemoveConstraint(
            model_name="order",
            name="positive_total_price",
        ),
        migrations.RemoveConstraint(
            model_name="orderitem",
            name="positive_quantity",
        ),
        migrations.RemoveConstraint(
            model_name="orderitem",
            name="positive_original_price",
        ),
        migrations.RemoveConstraint(
            model_name="orderitem",
            name="positive_new_price",
        ),
        migrations.RemoveConstraint(
            model_name="orderitem",
            name="correct_item_discount",
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity__gte", 1)), name="cart_positive_quantity"
            ),
        ),
        migrations.AddConstraint(
            model_name="couponcount",
            constraint=models.CheckConstraint(
                check=models.Q(("count__gte", 1)), name="coupon_count_positive_count"
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                check=models.Q(("total_price__gte", 1)),
                name="order_positive_total_price",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity__gte", 1)), name="item_positive_quantity"
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                check=models.Q(("original_price__gte", 1)),
                name="item_positive_original_price",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                check=models.Q(("new_price__gte", 0)), name="item_positive_new_price"
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                check=models.Q(("discount__gte", 0), ("discount__lt", 100)),
                name="item_correct_discount",
            ),
        ),
    ]
