# Generated by Django 4.0 on 2023-02-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_orderitem_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_accepted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_delivered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
