# Generated by Django 4.1.7 on 2023-03-20 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0006_clientsfavstores_client_fav_stores_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="fav_stores",
        ),
    ]
