# Generated by Django 4.0 on 2023-02-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_order_is_accepted_order_is_delivered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='new_price',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='original_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
