# Generated by Django 4.1.7 on 2023-03-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0007_alter_couponcount_count_order_valide_order"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("client_id__isnull", False),
                    ("store_id__isnull", False),
                    _connector="OR",
                ),
                name="valide_order",
            ),
        ),
    ]
