# Generated by Django 4.1.7 on 2023-03-20 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0007_remove_client_fav_stores"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ClientsFavStores",
        ),
    ]
