# Generated by Django 4.1.7 on 2023-03-06 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0008_remove_order_valide_order_order_valide_order"),
    ]

    operations = [
    ]
