# Generated by Django 4.0 on 2023-02-15 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_remove_order_client_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsedCoupon',
            new_name='OrderCoupon',
        ),
    ]
