# Generated by Django 4.1.7 on 2023-03-10 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0009_remove_order_valide_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="archived_by_client",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="archived_by_store",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ad_type",
                    models.CharField(
                        choices=[("Store", "store"), ("Product", "product")],
                        default="Store",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ads",
                        related_query_name="ad",
                        to="API.product",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ads",
                        related_query_name="ad",
                        to="API.store",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(default="", max_length=1000)),
                (
                    "ad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        related_query_name="image",
                        to="API.advertisement",
                    ),
                ),
            ],
        ),
    ]
