# Generated by Django 4.1.7 on 2023-03-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0009_clientfavstores_clientfavstores_unique_client_store"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="fav_stores",
            field=models.ManyToManyField(through="API.ClientFavStores", to="API.store"),
        ),
    ]
