# Generated by Django 4.1.7 on 2023-03-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0010_order_archived_by_client_order_archived_by_store_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="coupon",
            name="correct_coupon_discount",
        ),
        migrations.RemoveConstraint(
            model_name="notification",
            name="valide_notification",
        ),
        migrations.AlterField(
            model_name="coupon",
            name="discount",
            field=models.IntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name="coupon",
            constraint=models.CheckConstraint(
                check=models.Q(("discount__gte", 1), ("discount__lte", 100)),
                name="correct_coupon_discount",
            ),
        ),
        migrations.AddConstraint(
            model_name="couponcount",
            constraint=models.UniqueConstraint(
                fields=("client_id", "coupon_id"), name="unique_client_coupon"
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("client_id__isnull", True),
                    ("store_id__isnull", True),
                    _connector="XOR",
                ),
                name="valide_notification",
                violation_error_message="both client and store are/aren't null",
            ),
        ),
    ]
