# Generated by Django 4.1.7 on 2023-03-20 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0010_client_fav_stores"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="coupons",
            field=models.ManyToManyField(through="API.OrderCoupon", to="API.coupon"),
        ),
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(through="API.OrderProduct", to="API.product"),
        ),
    ]
