# Generated by Django 4.0 on 2023-02-15 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_rename_usedcoupon_ordercoupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='district',
            new_name='daira',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='province',
            new_name='wilaya',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='district',
            new_name='daira',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='province',
            new_name='wilaya',
        ),
        migrations.RemoveField(
            model_name='ordercoupon',
            name='client',
        ),
    ]
