# Generated by Django 4.0 on 2023-02-15 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_rename_district_client_daira_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercoupon',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.client'),
        ),
    ]
