# Generated by Django 4.1.7 on 2023-03-20 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0011_order_coupons_order_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="clients",
            field=models.ManyToManyField(through="API.CouponCount", to="API.client"),
        ),
    ]
