# Generated by Django 4.1.7 on 2023-03-20 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0012_coupon_clients"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CouponCount",
            new_name="CouponClient",
        ),
        migrations.RemoveField(
            model_name="coupon",
            name="clients",
        ),
    ]
