# Generated by Django 4.1.7 on 2023-03-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0013_rename_couponcount_couponclient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="clients",
            field=models.ManyToManyField(through="API.CouponClient", to="API.client"),
        ),
    ]
