# Generated by Django 4.0 on 2023-02-18 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_rename_daira_client_commune_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pack_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='API.packtype'),
        ),
    ]
