# Generated by Django 4.1.7 on 2023-03-20 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0014_coupon_clients"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="items",
            new_name="products",
        ),
    ]
