# Generated by Django 4.1.7 on 2023-03-21 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0015_rename_items_cart_products"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ClientFavStores",
            new_name="ClientFavStore",
        ),
        migrations.RenameModel(
            old_name="GroupClients",
            new_name="GroupClient",
        ),
        migrations.RenameModel(
            old_name="StoreFavClients",
            new_name="StoreFavClient",
        ),
        migrations.RemoveField(
            model_name="client",
            name="fav_stores",
        ),
        migrations.RemoveField(
            model_name="group",
            name="clients",
        ),
        migrations.RemoveField(
            model_name="store",
            name="fav_clients",
        ),
    ]
