# Generated by Django 4.1.7 on 2023-03-21 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0016_rename_clientfavstores_clientfavstore_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="fav_stores",
            field=models.ManyToManyField(through="API.ClientFavStore", to="API.store"),
        ),
        migrations.AddField(
            model_name="group",
            name="clients",
            field=models.ManyToManyField(through="API.GroupClient", to="API.client"),
        ),
        migrations.AddField(
            model_name="store",
            name="fav_clients",
            field=models.ManyToManyField(through="API.StoreFavClient", to="API.client"),
        ),
    ]
