# Generated by Django 4.0 on 2023-02-20 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0016_alter_coupon_store_alter_group_store_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercoupon',
            name='client',
        ),
    ]
