# Generated by Django 4.1.7 on 2023-03-21 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0017_client_fav_stores_group_clients_store_fav_clients"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="couponclient",
            name="coupon_count_positive_count",
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orderproducts",
                related_query_name="orderproduct",
                to="API.order",
            ),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orderproducts",
                related_query_name="orderproduct",
                to="API.product",
            ),
        ),
        migrations.AddConstraint(
            model_name="couponclient",
            constraint=models.CheckConstraint(
                check=models.Q(("count__gte", 1)), name="coupon_positive_count"
            ),
        ),
    ]
