# Generated by Django 4.1.7 on 2023-03-21 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0018_remove_couponclient_coupon_count_positive_count_and_more"),
    ]

    operations = [
    ]
