# Generated by Django 4.1.7 on 2023-02-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0018_alter_order_error_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="error_description",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
