# Generated by Django 4.1.7 on 2023-02-25 19:14

import API.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("API", "0019_alter_order_error_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="order",
            name="error_description",
        ),
        migrations.RemoveField(
            model_name="order",
            name="is_accepted",
        ),
        migrations.RemoveField(
            model_name="order",
            name="is_delivered",
        ),
        migrations.AddField(
            model_name="category",
            name="image_url",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="client",
            name="address",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="client",
            name="commune",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="client",
            name="created_at",
            field=models.IntegerField(default=API.models.get_now_stamp),
        ),
        migrations.AlterField(
            model_name="client",
            name="e_mail",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="client",
            name="full_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="client",
            name="password",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone_number",
            field=models.CharField(default="0", max_length=20),
        ),
        migrations.AlterField(
            model_name="client",
            name="shop_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="client",
            name="wilaya",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="coupon_type",
            field=models.CharField(
                choices=[
                    ("Product", "Product"),
                    ("Category", "Category"),
                    ("All", "All"),
                ],
                default="All",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="created_at",
            field=models.IntegerField(default=API.models.get_now_stamp),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="discount",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="max_nbr_uses",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="store",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coupons",
                related_query_name="coupon",
                to="API.store",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="coupon",
            name="string",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="group",
            name="created_at",
            field=models.IntegerField(default=API.models.get_now_stamp),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="group",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                related_query_name="group",
                to="API.store",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.IntegerField(default=API.models.get_now_stamp),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="ordercoupon",
            name="coupon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordercoupons",
                related_query_name="ordercoupon",
                to="API.coupon",
            ),
        ),
        migrations.AlterField(
            model_name="ordercoupon",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordercoupons",
                related_query_name="ordercoupon",
                to="API.order",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="discount",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="new_price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orderitems",
                related_query_name="orderitem",
                to="API.order",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="original_price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="packtype",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.IntegerField(default=API.models.get_now_stamp),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="nbr_units",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="product",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                related_query_name="product",
                to="API.store",
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="address",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="store",
            name="commune",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="store",
            name="created_at",
            field=models.IntegerField(default=API.models.get_now_stamp),
        ),
        migrations.AlterField(
            model_name="store",
            name="e_mail",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="store",
            name="full_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="store",
            name="image_url",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="store",
            name="password",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="store",
            name="phone_number",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="store",
            name="store_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="store",
            name="wilaya",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.CreateModel(
            name="OrderState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("Accepted", "Accepted"), ("Refused", "Refused")],
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(default="")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orderstates",
                        related_query_name="orderstate",
                        to="API.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_1_id", models.PositiveIntegerField()),
                ("user_2_id", models.PositiveIntegerField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("Created", "Created"),
                            ("Updated", "Updated"),
                            ("Deleted", "Deleted"),
                            ("Accepted", "Accepted"),
                            ("Refused", "Refused"),
                            ("Canceled", "Canceled"),
                            ("Submited", "Submited"),
                            ("Sent", "Sent"),
                            ("Shipping", "Shipping"),
                            ("Delivered", "Delivered"),
                        ],
                        default="nothing",
                        max_length=100,
                    ),
                ),
                ("message", models.TextField(default="")),
                ("read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="API.order",
                    ),
                ),
                (
                    "user_1_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user_2_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CouponCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(default=0)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="couponcounts",
                        related_query_name="couponcount",
                        to="API.client",
                    ),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="couponcounts",
                        related_query_name="couponcount",
                        to="API.coupon",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cartitems",
                        related_query_name="cartitem",
                        to="API.cart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cartitems",
                        related_query_name="cartitem",
                        to="API.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cart",
            name="client",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carts",
                related_query_name="cart",
                to="API.client",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user_1_type", "user_1_id"],
                name="API_notific_user_1__d2cb6c_idx",
            ),
        ),
    ]
