# Generated by Django 4.1.7 on 2023-03-22 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0019_remove_couponclient_coupon_max_nbr_uses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="couponclient",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="couponclients",
                related_query_name="couponclient",
                to="API.client",
            ),
        ),
        migrations.AlterField(
            model_name="couponclient",
            name="coupon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="couponclients",
                related_query_name="couponclient",
                to="API.coupon",
            ),
        ),
    ]
