# Generated by Django 4.1.7 on 2023-03-22 01:25

import API.some_functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0020_alter_couponclient_client_alter_couponclient_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="created_at",
            field=models.IntegerField(default=API.some_functions.get_now_stamp),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="dir_path",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="category",
            name="dir_path",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="client",
            name="dir_path",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="dir_path",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="store",
            name="dir_path",
            field=models.CharField(default="", max_length=100),
        ),
    ]
