# Generated by Django 4.1.7 on 2023-03-22 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0021_advertisement_created_at_advertisement_dir_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupclient",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groupclients",
                related_query_name="groupclient",
                to="API.client",
            ),
        ),
    ]
