# Generated by Django 4.1.7 on 2023-02-26 07:36

import API.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0021_alter_cart_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderstate",
            name="time_stamp",
            field=models.IntegerField(default=API.models.get_now_stamp),
        ),
        migrations.AlterField(
            model_name="notification",
            name="action",
            field=models.CharField(
                choices=[
                    ("Created", "Created"),
                    ("Updated", "Updated"),
                    ("Deleted", "Deleted"),
                    ("Accepted", "Accepted"),
                    ("Refused", "Refused"),
                    ("Canceled", "Canceled"),
                    ("Submited", "Submited"),
                    ("Sent", "Sent"),
                    ("Completed", "Completed"),
                    ("Shipping", "Shipping"),
                    ("Delivered", "Delivered"),
                ],
                default="nothing",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="orderstate",
            name="state",
            field=models.CharField(
                choices=[
                    ("Created", "Created"),
                    ("Updated", "Updated"),
                    ("Deleted", "Deleted"),
                    ("Accepted", "Accepted"),
                    ("Refused", "Refused"),
                    ("Canceled", "Canceled"),
                    ("Submited", "Submited"),
                    ("Sent", "Sent"),
                    ("Completed", "Completed"),
                    ("Shipping", "Shipping"),
                    ("Delivered", "Delivered"),
                ],
                max_length=100,
            ),
        ),
    ]
