# Generated by Django 4.1.7 on 2023-03-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0022_alter_groupclient_client"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="advertisement",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("ad_type__iexact", "product"),
                    ("product_id__isnull", False),
                    _negated=True,
                ),
                name="valide_ad",
            ),
        ),
    ]
