# Generated by Django 4.1.7 on 2023-02-26 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("API", "0022_orderstate_time_stamp_alter_notification_action_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Notification",
            new_name="OrderNotification",
        ),
        migrations.RenameIndex(
            model_name="ordernotification",
            new_name="API_orderno_user_1__2ace11_idx",
            old_name="API_notific_user_1__d2cb6c_idx",
        ),
    ]
