# Generated by Django 4.1.7 on 2023-03-23 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0023_advertisement_valide_ad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartproduct",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cartproducts",
                related_query_name="cartproduct",
                to="API.cart",
            ),
        ),
        migrations.AlterField(
            model_name="cartproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cartproducts",
                related_query_name="cartproduct",
                to="API.product",
            ),
        ),
    ]
