# Generated by Django 4.1.7 on 2023-02-26 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0023_rename_notification_ordernotification_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="ordernotification",
            name="API_orderno_user_1__2ace11_idx",
        ),
    ]
