# Generated by Django 4.1.7 on 2023-02-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0024_remove_ordernotification_api_orderno_user_1__2ace11_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderstate",
            name="state",
            field=models.CharField(
                choices=[
                    ("Created", "Created"),
                    ("Updated", "Updated"),
                    ("Deleted", "Deleted"),
                    ("Accepted", "Accepted"),
                    ("Refused", "Refused"),
                    ("Canceled", "Canceled"),
                    ("Submited", "Submited"),
                    ("Sent", "Sent"),
                    ("Completed", "Completed"),
                    ("Shipping", "Shipping"),
                    ("Delivered", "Delivered"),
                ],
                default="nothing",
                max_length=100,
            ),
        ),
    ]
