# Generated by Django 4.1.7 on 2023-03-23 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0024_alter_cartproduct_cart_alter_cartproduct_product"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="orderproduct",
            name="item_positive_quantity",
        ),
        migrations.RemoveConstraint(
            model_name="orderproduct",
            name="item_positive_original_price",
        ),
        migrations.RemoveConstraint(
            model_name="orderproduct",
            name="item_positive_new_price",
        ),
        migrations.RemoveConstraint(
            model_name="orderproduct",
            name="item_correct_discount",
        ),
        migrations.AddConstraint(
            model_name="orderproduct",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity__gte", 1)), name="product_positive_quantity"
            ),
        ),
        migrations.AddConstraint(
            model_name="orderproduct",
            constraint=models.CheckConstraint(
                check=models.Q(("original_price__gte", 1)),
                name="product_positive_original_price",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderproduct",
            constraint=models.CheckConstraint(
                check=models.Q(("new_price__gte", 0)), name="product_positive_new_price"
            ),
        ),
        migrations.AddConstraint(
            model_name="orderproduct",
            constraint=models.CheckConstraint(
                check=models.Q(("discount__gte", 0), ("discount__lt", 100)),
                name="product_correct_discount",
            ),
        ),
    ]
