# Generated by Django 4.1.7 on 2023-03-24 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0025_remove_orderproduct_item_positive_quantity_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="couponclient",
            name="coupon_positive_count",
        ),
        migrations.AddConstraint(
            model_name="couponclient",
            constraint=models.CheckConstraint(
                check=models.Q(("count__gte", 0)), name="coupon_positive_count"
            ),
        ),
    ]
