# Generated by Django 4.1.7 on 2023-02-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0025_alter_orderstate_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordernotification",
            name="action",
            field=models.CharField(
                choices=[
                    ("Created", "Created"),
                    ("Updated", "Updated"),
                    ("Deleted", "Deleted"),
                    ("Accepted", "Accepted"),
                    ("Refused", "Refused"),
                    ("Canceled", "Canceled"),
                    ("Submited", "Submited"),
                    ("Sent", "Sent"),
                    ("Completed", "Completed"),
                    ("Shipping", "Shipping"),
                    ("Delivered", "Delivered"),
                ],
                default="Created",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="orderstate",
            name="state",
            field=models.CharField(
                choices=[
                    ("Created", "Created"),
                    ("Updated", "Updated"),
                    ("Deleted", "Deleted"),
                    ("Accepted", "Accepted"),
                    ("Refused", "Refused"),
                    ("Canceled", "Canceled"),
                    ("Submited", "Submited"),
                    ("Sent", "Sent"),
                    ("Completed", "Completed"),
                    ("Shipping", "Shipping"),
                    ("Delivered", "Delivered"),
                ],
                default="Created",
                max_length=100,
            ),
        ),
    ]
