# Generated by Django 4.1.7 on 2023-02-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0026_alter_ordernotification_action_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="coupon",
            constraint=models.UniqueConstraint(
                fields=("string", "store_id"), name="unique_coupon"
            ),
        ),
    ]
