# Generated by Django 4.1.7 on 2023-03-24 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0026_remove_couponclient_coupon_positive_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordercoupon",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ordercoupons",
                related_query_name="ordercoupon",
                to="API.coupon",
            ),
        ),
    ]
