# Generated by Django 4.1.7 on 2023-03-24 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0027_alter_ordercoupon_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="current_state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_orders",
                related_query_name="current_order",
                to="API.orderstate",
            ),
        ),
    ]
