# Generated by Django 4.1.7 on 2023-02-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0027_coupon_unique_coupon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="target_id",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
