# Generated by Django 4.1.7 on 2023-03-24 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0028_order_current_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderstate",
            name="updated_by_store",
            field=models.BooleanField(default=False),
        ),
    ]
