# Generated by Django 4.1.7 on 2023-03-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0029_orderstate_updated_by_store"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderstate",
            name="updated_by_store",
            field=models.BooleanField(default=True),
        ),
    ]
